"""empty message

Revision ID: 1690e4fbc4e0
Revises: 24e65e1dcbc2
Create Date: 2022-05-29 16:21:39.267261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1690e4fbc4e0'
down_revision = '24e65e1dcbc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marvel_characters', sa.Column('image', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('marvel_characters', 'image')
    # ### end Alembic commands ###
