"""empty message

Revision ID: 588b184a51e0
Revises: 1690e4fbc4e0
Create Date: 2022-06-11 11:15:26.212382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '588b184a51e0'
down_revision = '1690e4fbc4e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marvel_characters', sa.Column('hours_available', sa.Integer(), nullable=True))
    op.add_column('marvel_characters', sa.Column('hourly_cost', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('marvel_characters', 'hourly_cost')
    op.drop_column('marvel_characters', 'hours_available')
    # ### end Alembic commands ###
