"""empty message

Revision ID: e00003de211d
Revises: a70af2c83431
Create Date: 2022-05-25 18:08:05.109563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e00003de211d'
down_revision = 'a70af2c83431'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username_id', sa.String(length=100), nullable=False))
    op.add_column('user', sa.Column('wins', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('losses', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'user', ['username_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'losses')
    op.drop_column('user', 'wins')
    op.drop_column('user', 'username_id')
    # ### end Alembic commands ###
